### ISSUE TITLE
Only first sensor reading works, repeated readings never call callback

### ISSUE THREAD

**Issue by erikmav** [depuits/pigpio-dht#2]
While using pigpio-dht in sensor project that stays online for days at a time, the first sensor reading works but successive readings hit checksum conditions in the sensor callback logic and never produce a callback after the first. This bug was tracked down to the need to set the data pin high and store the current pigpio tick count before taking the next reading. Additional needed API updates to pigpio were added in https://github.com/fivdi/pigpio/pull/65 which were published as pigpio version 1.2.0. PR #1 uses that functionality to fix this bug.

**Comment by depuits** [comment]
Fixed with PR #1.

**Comment by erikmav** [comment]
Thanks for accepting the related PR! pigpio-dht package version 1.1.1 verified and deployed to my production environment.
